author: 'LS_Hower' # 作者名称
author_avatar: 'https://raw.githubusercontent.com/LS-Hower/LS-Hower/refs/heads/main/gan.png' # 作者头像
author_text: '学生。' # 作者信息
social: # 社交链接
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/LS-Hower'
  - title: '首页'
    icon: 'home'
    link: 'https://ls-hower.github.io'
# background: '' # 主题背景
menu: # 页眉菜单项目
  '关于我': /about
  '朋友们': /friends
  '其他项目': /projects
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
